name: imageproject
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  retrofit: 4.0.1
  mockito: 5.4.2
  json_annotation: 4.8.1
  flutter_screenutil: 5.8.4
  retrofit_generator: 7.0.8
  cached_network_image: 3.2.3
  equatable: 2.0.5
  dartz: 0.10.1
  shared_preferences: 2.2.0
  flutter_bloc: 8.1.3
  dio: 5.3.0
  google_fonts: 5.1.0
  go_router: 9.0.2
  get_it: 7.6.0

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  build_runner: 2.4.6

  json_serializable: 6.7.1
  mock_web_server: 5.0.0-nullsafety.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/


  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
